title:              Portfolio.
email:              vipin.ragashetti@gmail.com
description:        Vipin Ragashetti
author:             Vipin Ragashetti

# Social Profiles
#twitter_username:   #SBootstrap
github_username:    vipin-tech
#facebook_username:  #StartBootstrap
linkedin_username:  vipinragashetti

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"


# Site Author
author:
  name             : "Vipin Ragashetti"
  avatar           : /assets/images/photo.jpg
  bio              : "Avid Tech Reader, API Guy, Pythonista, Linux Administration."
  location         : "Curating the Web"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:vipin.ragashetti@gmail.com
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/RagashettiVipin"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
